name: bloc5-indiv-recette
#version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: docker/recette/php/Dockerfile
    #image: bloc5-indiv:recette
    container_name: bloc5-indiv-recette-php
    ports:
      - "8081:80"
    volumes:
      - storage_recette:/var/www/html/public/storage
    environment:
      APP_ENV: ${APP_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      MAILTRAP_HOST: ${MAILTRAP_HOST}
      MAILTRAP_PORT: ${MAILTRAP_PORT}
      MAILTRAP_USER: ${MAILTRAP_USER}
      MAILTRAP_PASS: ${MAILTRAP_PASS}
      MAILTRAP_FROM: ${MAILTRAP_FROM}
    depends_on:
      mysql:
        condition: service_healthy
  
  mysql:
    image: mariadb:10.11
    container_name: bloc5-indiv-recette-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data_recette:/var/lib/mysql
      - ./sql/import.sql:/docker-entrypoint-initdb.d/import.sql:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
  
  phpmyadmin:
    profiles:
      - disabled

volumes:
  mysql_data_recette:
  storage_recette: