name: bloc5-indiv-dev
services:
  php:
    build:
      context: ./docker/dev/php
      dockerfile: Dockerfile
    #image: bloc5-indiv:dev
    container_name: bloc5-indiv-dev-php
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    ports:
      - "${APP_PORT:-8080}:80"
    environment:
      APP_ENV: ${APP_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      MAILTRAP_HOST: ${MAILTRAP_HOST}
      MAILTRAP_PORT: ${MAILTRAP_PORT}
      MAILTRAP_USER: ${MAILTRAP_USER}
      MAILTRAP_PASS: ${MAILTRAP_PASS}
      MAILTRAP_FROM: ${MAILTRAP_FROM}
    depends_on:
      mysql:
        condition: service_healthy
  
  mysql:
    image: mariadb:10.11
    container_name: bloc5-indiv-dev-mysql
    ports:
      - "${DB_PORT_EXPOSE:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data_dev:/var/lib/mysql
      - ./sql/import.sql:/docker-entrypoint-initdb.d/import.sql:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: bloc5-indiv-dev-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8090:80"
    depends_on:
      - mysql

volumes:
  mysql_data_dev: